language: ruby
rvm:
  - 2.0.0
env:
  - DB=postgresql DATABASE_TEST_NAME=omniauth_rails_test DATABASE_TEST_USERNAME=postgres
before_script:
  - psql -c 'create database omniauth_rails_test' -U postgres
script:
  - bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake test
